version: '1.0'
services:
  app:
    container_name: muscle-brain-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - server-network
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    container_name: muscle-brain-db
    networks:
      - server-network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  database_test:
    image: postgres:12.1-alpine
    container_name: app_database_test
    networks:
      - server-network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app_database_test
    ports:
      - "5433:5432"
  adminer:
    image: adminer
    restart: always
    networks:
      - server-network
    ports:
      - 8080:8080
volumes:
  postgres:
networks:
  server-network:
    driver: bridge
